"""MP law illustrations and fixed mathematical constructions; no new null simulation."""
import argparse,math
from pathlib import Path
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
plt.rcParams.update({"svg.fonttype":"none","svg.hashsalt":"a09-rmt-04-mp","font.family":"DejaVu Sans","font.size":26,"axes.labelsize":24,"xtick.labelsize":22,"ytick.labelsize":22,"axes.spines.top":False,"axes.spines.right":False})
BLUE="#2563EB";PURPLE="#7C3AED";GREEN="#059669";AMBER="#D97706";GRAY="#64748B";BG="#F8FAFC"
def axes(fig,rect=(.22,.31,.66,.4)):
 ax=fig.add_axes(rect,facecolor=BG);ax.grid(color="#CBD5E1",alpha=.65);return ax
def mp(gamma,variance=1,size=10001):
 a=variance*(1-np.sqrt(gamma))**2;b=variance*(1+np.sqrt(gamma))**2;x=np.linspace(a,b,size);f=np.sqrt(np.maximum(0,(b-x)*(x-a)))/(2*np.pi*gamma*variance*x);return x,f,a,b
def main(output):
 key=output.stem.removeprefix("A09-RMT-04-");wide=key in ["positive-bulk-and-zero-mass","bulk-fraction-versus-maximum","candidate-affects-fitted-null-scale"];w,h=(1200,820) if wide else (520,1040);fig=plt.figure(figsize=(w/72,h/72),facecolor=BG)
 if key=="empirical-cdf-from-all-values":
  values=np.array([.3,.5,.6,.7,.8,1,1.2,1.4,1.7,2]);x=np.r_[0,values,2.3];cdf=np.r_[0,np.arange(1,11)/10,1];ax=axes(fig);ax.step(x,cdf,where="post",color=PURPLE,lw=3);ax.axvline(1,color=AMBER,ls="--",lw=2);ax.scatter([1],[.6],s=70,color=AMBER,zorder=5);ax.set(xlim=(0,2.3),ylim=(0,1.1),xlabel="Threshold t",ylabel="Fraction of eigenvalues ≤ t");ax.set_xticks([0,1,2]);ax.set_yticks([0,.5,1]);fig.text(.077,.95,"Count all values of one matrix",fontsize=26);fig.text(.077,.87,"Illustrative fixed list: d = 10",fontsize=26);fig.text(.077,.79,"At t = 1: 6 of 10 values",fontsize=27,color=AMBER);fig.text(.077,.20,"Empirical CDF F(1) = 0.6",fontsize=27);fig.text(.077,.13,"Not a repeated-largest-value law",fontsize=24);fig.text(.077,.06,"A fixed spectrum, not a simulation",fontsize=24,color=GRAY)
 elif key=="mp-mean-and-midpoint":
  x,f,a,b=mp(.25);ax=axes(fig);ax.fill_between(x,0,f,color=PURPLE,alpha=.15);ax.plot(x,f,color=PURPLE,lw=3);ax.axvline(1,color=AMBER,ls=":",lw=2);ax.axvline(1.25,color=GREEN,ls="--",lw=2);ax.set(xlim=(0,2.5),ylim=(0,1),xlabel="Limiting eigenvalue λ",ylabel="MP density");ax.set_xticks([.25,1,2.25]);ax.set_yticks([0,.5,1]);fig.text(.077,.95,"A bulk is not uniform.",fontsize=27);fig.text(.077,.88,"σ² = 1, γ = 0.25",fontsize=28);fig.text(.077,.82,"Mean = 1  ···",fontsize=27,color=AMBER);fig.text(.077,.76,"Interval midpoint = 1.25  - -",fontsize=25,color=GREEN);fig.text(.077,.20,"Nonzero support: [0.25, 2.25]",fontsize=25);fig.text(.077,.13,"The density weights the mean.",fontsize=25);fig.text(.077,.06,"Finite sample averages can differ.",fontsize=24,color=GRAY)
 elif key=="aspect-ratio-bulk-edges":
  g=np.linspace(.001,4,700);ax=axes(fig);ax.plot(g,(1-np.sqrt(g))**2,color=PURPLE,lw=3);ax.plot(g,(1+np.sqrt(g))**2,"--",color=GREEN,lw=3);ax.scatter([.25,.25],[.25,2.25],s=60,color=[PURPLE,GREEN],zorder=4);ax.set(xlim=(0,4.2),ylim=(0,10),xlabel="Aspect ratio γ",ylabel="Nonzero bulk edge");ax.set_xticks([.25,1,4]);ax.set_yticks([0,5,10]);fig.text(.077,.95,"Nonzero bulk edges: σ² = 1",fontsize=26);fig.text(.077,.87,"Lower λ− = (1 − √γ)²  —",fontsize=26,color=PURPLE);fig.text(.077,.79,"Upper λ+ = (1 + √γ)²  - -",fontsize=25,color=GREEN);fig.text(.077,.20,"Width = 4√γ; γ → 0 narrows it.",fontsize=24);fig.text(.077,.13,"γ > 1: positive λ− plus zero mass",fontsize=23);fig.text(.077,.06,"Nonzero edges do not count zeros.",fontsize=24,color=GRAY)
 elif key=="noise-variance-bulk-rescaling":
  ax=axes(fig,(.30,.31,.58,.40))
  for y,scale,col in [(1,1,BLUE),(0,2,GREEN)]:ax.plot([.25*scale,2.25*scale],[y,y],color=col,lw=8);ax.scatter([.25*scale,2.25*scale],[y,y],s=55,color=col)
  ax.set(xlim=(0,5),ylim=(-.5,1.5),xlabel="Eigenvalue λ");ax.set_xticks([0,2.5,5]);ax.set_yticks([0,1],["σ² = 2","σ² = 1"]);fig.text(.077,.95,"Variance rescales both edges.",fontsize=27);fig.text(.077,.87,"Same γ = 0.25",fontsize=28);fig.text(.077,.79,"Blue: variance 1; green: variance 2",fontsize=23);fig.text(.077,.20,"[0.25, 2.25] → [0.5, 4.5]",fontsize=26);fig.text(.077,.13,"Scale is σ², not σ.",fontsize=28);fig.text(.077,.06,"Intervals mark support, not density.",fontsize=24,color=GRAY)
 elif key=="positive-bulk-and-zero-mass":
  ax=axes(fig,(.10,.29,.30,.42));ax.bar([0,1],[.5,.5],color=[BLUE,GREEN],edgecolor=GRAY,hatch="//");ax.set(xlim=(-.6,1.6),ylim=(0,.65),xlabel="Part of all d eigenvalues",ylabel="Probability mass");ax.set_xticks([0,1],["Zero","Positive"]);ax.set_yticks([0,.5]);ax.set_title("Mass split",fontsize=29,pad=27)
  x,f,a,b=mp(2);ax=axes(fig,(.62,.29,.33,.42));ax.plot(x,2*f,color=GREEN,lw=3);ax.fill_between(x,0,2*f,color=GREEN,alpha=.15);ax.set(xlim=(0,6),ylim=(0,.6),xlabel="Positive eigenvalue λ",ylabel="Conditional density");ax.set_xticks([a,3,b],[f"{a:.3f}","3",f"{b:.3f}"]);ax.set_yticks([0,.3,.6]);ax.set_title("Given λ > 0: density",fontsize=27,pad=27);fig.text(.04,.94,"γ = 2: a zero atom and a separate positive bulk",fontsize=30);fig.text(.04,.83,"Zero mass = 1−1/γ = 0.5; positive mass = 1/γ = 0.5",fontsize=29);fig.text(.04,.14,"Positive lower edge ≈ 0.172; conditional density integrates to 1.",fontsize=28);fig.text(.04,.07,"Do not compare atom mass with a density height.",fontsize=29,color=GRAY)
 elif key=="gamma-one-finite-centering-zero":
  d=np.geomspace(40,1600,250);ax=axes(fig);ax.plot(d,1/d,color=BLUE,lw=3);ax.axhline(0,color=GRAY,ls="--",lw=2);ax.set_xscale("log");ax.set(xlim=(30,2100),ylim=(-.001,.028),xlabel="Square dimension d = n",ylabel="Zero fraction");ax.set_xticks([40,400,1600],["40","400","1600"]);ax.set_xticks([],minor=True);ax.set_yticks([0,.01,.02]);fig.text(.077,.95,"γ = 1: one zero is not a zero mass",fontsize=24);fig.text(.077,.87,"Centered Gaussian: fraction 1/d  —",fontsize=24,color=BLUE);fig.text(.077,.79,"Uncentered full rank: fraction 0 - -",fontsize=23,color=GRAY);fig.text(.077,.20,"One centered zero at each finite d",fontsize=25);fig.text(.077,.13,"Limiting zero mass remains 0.",fontsize=26);fig.text(.077,.06,"Additional constraints can add zeros.",fontsize=23,color=GRAY)
 elif key=="bulk-fraction-versus-maximum":
  x,f,a,b=mp(.25);cdf=np.r_[0,np.cumsum((f[1:]+f[:-1])/2*np.diff(x))];cdf/=cdf[-1];dims=np.unique(np.geomspace(10,1000,80).astype(int));fractions=[];maxima=[]
  for d in dims:
   remaining=np.interp((np.arange(d-1)+.5)/(d-1),cdf,x);values=np.r_[remaining,10];fractions.append(np.mean(values>b));maxima.append(values.max())
  for rect,vals,label,col,yl in [((.10,.29,.31,.42),fractions,"Outside-bulk fraction",BLUE,(0,.11)),((.63,.29,.31,.42),maxima,"Largest eigenvalue",AMBER,(0,11))]:
   ax=axes(fig,rect);ax.plot(dims,vals,color=col,lw=3);ax.set_xscale("log");ax.set(xlim=(8,1300),ylim=yl,xlabel="Dimension d",ylabel=label);ax.set_xticks([10,100,1000],["10","100","1000"]);ax.set_xticks([],minor=True);ax.set_yticks([0,.05,.1] if col==BLUE else [0,5,10]);ax.set_title("Fraction 1/d → 0" if col==BLUE else "Maximum stays 10",fontsize=28,pad=27)
  fig.text(.04,.94,"One constructed outlier can vanish from the ESD fraction",fontsize=28);fig.text(.04,.83,"Remaining values: MP bulk quantiles; one value: 10",fontsize=29);fig.text(.04,.14,"Small spectral fraction does not control the maximum.",fontsize=29);fig.text(.04,.07,"Deterministic construction, not an iid-noise simulation",fontsize=28,color=GRAY)
 elif key=="candidate-affects-fitted-null-scale":
  values=np.r_[np.ones(9),10];scale=values.mean();ax=axes(fig,(.10,.29,.31,.42));ax.scatter(np.arange(1,11),values,color=BLUE,s=55,zorder=4);ax.scatter([10],[10],color=AMBER,s=85,zorder=5);ax.set(xlim=(0,11),ylim=(0,11),xlabel="Eigenvalue index",ylabel="Illustrative eigenvalue");ax.set_xticks([1,5,10]);ax.set_yticks([0,5,10]);ax.set_title("Nine ones; one ten",fontsize=29,pad=27)
  ax=axes(fig,(.64,.29,.31,.42));ax.scatter([2.25,scale*2.25],[1,0],s=95,color=[GREEN,PURPLE],zorder=4);ax.axvline(10,color=AMBER,ls="--",lw=2);ax.set(xlim=(0,11),ylim=(-.5,1.5),xlabel="Fitted upper edge λ+");ax.set_xticks([0,5,10]);ax.set_yticks([0,1],["All fit","Bulk fit"]);ax.set_title("Same γ = 0.25",fontsize=29,pad=27)
  fig.text(.04,.94,"Including a candidate also changes the fitted null scale",fontsize=29);fig.text(.04,.83,"Exclude candidate: scale 1; include all: scale 1.9",fontsize=29);fig.text(.04,.14,"Upper edge changes 2.25 → 4.275; candidate remains 10.",fontsize=28);fig.text(.04,.07,"A fitting-dependence calculation, not proof of task signal",fontsize=27,color=GRAY)
 elif key=="isotropic-not-independent-coordinates":
  theta=np.linspace(0,2*np.pi,361);ax=axes(fig);ax.plot(np.sqrt(2)*np.cos(theta),np.sqrt(2)*np.sin(theta),color=PURPLE,lw=3);guide=np.arange(8)*np.pi/4;ax.scatter(np.sqrt(2)*np.cos(guide),np.sqrt(2)*np.sin(guide),color=PURPLE,s=45,zorder=4);ax.set(xlim=(-1.8,1.8),ylim=(-1.8,1.8),xlabel="Coordinate x₁",ylabel="Coordinate x₂");ax.set_aspect("equal");ax.set_xticks([-1,0,1]);ax.set_yticks([-1,0,1]);fig.text(.077,.95,"Isotropic does not imply entry iid.",fontsize=24);fig.text(.077,.87,"Uniform angle on a radius √2 circle",fontsize=24);fig.text(.077,.79,"E x = 0; covariance I₂",fontsize=28,color=PURPLE);fig.text(.077,.20,"Constraint: x₁² + x₂² = 2",fontsize=27);fig.text(.077,.13,"Coordinates cannot be independent.",fontsize=24);fig.text(.077,.06,"Support curve; dots are guide angles.",fontsize=23,color=GRAY)
 else:raise ValueError(key)
 output.parent.mkdir(parents=True,exist_ok=True);fig.savefig(output,format="svg",metadata={"Date":None});plt.close(fig)
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--output",type=Path,required=True);main(p.parse_args().output)
